version: '3.8'

services:
  app:
    build: .
    container_name: webapp_template_app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: webapp_template_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-webapp_template}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: webapp_template_redis
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  postgres_data:
